### ISSUE TITLE
Arduino videos

### ISSUE THREAD

**Issue by josephfarahat** [josephfarahat/ASUMobiCarG58#1]
ya shabab di playlist lel arduino
https://www.youtube.com/watch?v=48pLh8gQ6eg&list=PLcoY6oF0HdM047JvJKx126PHAfeoLfnAR

**Comment by josephfarahat** [comment]
we dah lel github 
https://www.youtube.com/watch?v=3RjQznt-8kE&list=PL4cUxeGkcC9goXbgTDQ0n_4TBzOO0ocPR

**Comment by amgadosama** [comment]
shbaab dah program simulation online tab3 adobe 
https://circuits.io/
