### ISSUE TITLE
real vs fake arduino board

### ISSUE THREAD

**Issue by HMarsafy** [josephfarahat/ASUMobiCarG58#5]
original 👍 
![uno_orig](https://user-images.githubusercontent.com/36539806/37821012-1965561e-2e8b-11e8-9e7f-e75fbd8c636e.jpg)
![arduinouno-bottomsmall2](https://user-images.githubusercontent.com/36539806/37821030-26d1fc08-2e8b-11e8-9db3-ab606b7520bc.jpg)

**Comment by HMarsafy** [comment]
fake 👎 
![uno_count](https://user-images.githubusercontent.com/36539806/37821055-382644b4-2e8b-11e8-9b58-2b40be820140.jpg)
![uno_back_f](https://user-images.githubusercontent.com/36539806/37821063-4076a12c-2e8b-11e8-9f9d-7ac9577a4006.jpg)

**Comment by josephfarahat** [comment]
ours is the counterfeit
